# Generated by Django 4.0.3 on 2022-03-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermanagement',
            name='picture',
            field=models.ImageField(blank=True, default='default', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customermanagement',
            name='tag',
            field=models.CharField(default='default.png', max_length=50),
            preserve_default=False,
        ),
    ]
