# Generated by Django 4.0.3 on 2022-03-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customermanagement_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermanagement',
            name='tag',
            field=models.CharField(default='defaultTag', max_length=50),
        ),
    ]
